### ISSUE TITLE
[Secret NFTs] Error management

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-js#135]
## Todo

- [x] list + log properly SGX API errors
- [x] log properly IPFS errors
- [x] handle IPFS metadata validation (throw TypeError or use a validator e.g. JOI)
- [x] handle SGX upload retry
- [x] handle error: enclave is not reachable

**Comment by ipapandinas** [comment]
PR: #142
